fast-glob>3.0.0 doesn't support backslashes as path separator, fix it by normalize the path
benyap/resolve-tspaths pull request #20
Opened 2022-01-20 08:22 UTC by qiaoruntao

Hello,
        The fast-glob package since 3.0.0 does not support backslashes as path separator. So i fix it by normalizing the path. I also change the test file so it can correctly detect this problem on windows platform.

2022-01-20 13:35 UTC, benyap commented
Hey @qiaoruntao, thanks for your PR! I'm not using a Windows machine so I appreciate this.

Do you mind running `yarn format` before I merge this in?

2022-01-20 13:36 UTC, benyap requested changes
Please run `yarn format` to ensure code style consistency

2022-01-20 14:50 UTC, qiaoruntao commented
Hello, I have run the yarn format. Thanks for you remind :smile:

2022-01-21 00:38 UTC, benyap approved these changes

2022-01-21 00:38 UTC, merged

2022-01-21 00:42 UTC, benyap commented
@all-contributors please add @qiaoruntao for code and test